### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [zavalacl/week6proj#1]
It looks like there's some pretty wild indentation in `app.rb`. Can you fix it so that the indentation starts at zero and uses two-space tabs instead of hard-tabs? The resource below should help you do that.
### Ruby indentation

The standard indentation for Ruby (`.rb`) files is actually with two-space soft-tabs rather than hard-tabs. See if you can update your text editor to use two-space soft-tabs for all Ruby files. If you have trouble figuring it out, [this page may be helpful](https://github.com/chrisvfritz/tc359_cheatsheets/blob/master/ruby/indentation.md). If it's not, just let me know and I'll be happy to point you in the right direction.

---

Let me know when this is done and I'll take another look!

**Comment by zavalacl** [comment]
Hi you said you would look into atom indentation when we met today, don't forget to update the guide!

**Comment by chrisvfritz** [comment]
:+1: Thanks for the reminder. I've [updated the guide here](https://github.com/chrisvfritz/tc359_cheatsheets/blob/master/ruby/indentation.md#atom). :smiley:
